package com.inetpsa.pi201.manageprojects.rest.user;

/**
 * Source code generated by EA, don't modify outside EA
 * 
 * @author FRANK DUPUY
 * @version 1.0
 * @created 24-juin-2016 09:25:57
 */
public class UserRepresentation {

    private String login;
    private String name;
    private String firstName;

    public UserRepresentation() {

    }

    public UserRepresentation(String pLogin, String pFirstName, String pName) {
        this.login = pLogin;
        this.name = pName;
        this.firstName = pFirstName;

    }

    public void finalize() throws Throwable {

    }

    /**
     * @param newVal
     */
    public void setFirstName(String newVal) {
        this.firstName = newVal;
    }

    public String getFirstName() {
        return firstName;
    }

    /**
     * @param newVal
     */
    public void setName(String newVal) {
        this.name = newVal;
    }

    public String getName() {
        return name;
    }

    /**
     * @param newVal
     */
    public void setLogin(String newVal) {
        this.login = newVal;
    }

    public String getLogin() {
        return login;
    }

}