package com.inetpsa.pi201.domains.manageprojects.model.manageprojectsbudgetsresources.project;

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

import org.seedstack.business.domain.BaseAggregateRoot;

/**
 * Why getEntity ? getEntity voir pattern Factory Source code generated by EA, don't modify outside EA
 * 
 * @author FRANK DUPUY
 * @version 1.0
 * @created 18-mai-2016 10:06:26
 */
@Entity
public class Project extends BaseAggregateRoot<String> {

    @Id
    private String name;
    @OneToMany(cascade = { CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE }, fetch = FetchType.LAZY)
    private List<Deliverable> deliverables;

    private String responsableId;

    public Project() {
    }

    public void finalize() throws Throwable {
        super.finalize();
    }

    /**
     * method to define equals method used par seed stack to identify if 2 entity are equals ....
     */
    public String getEntityId() {
        return name;
    }

    /**
     * Adds a deliverable.
     *
     * @param p_nameDeliverable the Deliverable name
     * @param p_dateStart the Deliverable date start
     * @param p_dateEnd the Deliverable date end
     * @param p_dateNewStart the Deliverable date new start
     * @param p_dateNewEnd the Deliverable date new end
     */
    public void addDeliverable(String pNameDeliverable, Date pDateStart, Date pDateEnd, Date pDateNewStart, Date pDateNewEnd, String pComment) {
        Deliverable deliverable = new Deliverable();
        deliverable.setname(pNameDeliverable);
        deliverable.setdateStart(pDateStart);
        deliverable.setdateEnd(pDateEnd);
        deliverable.setdateNewStart(pDateNewStart);
        deliverable.setdateNewEnd(pDateNewEnd);
        deliverable.setcomment(pComment);
        deliverables.add(deliverable);
    }

    /**
     * Clears deliverables.
     */
    public void clearDeliverables() {
        deliverables.clear();
    }

    /**
     * @param newVal
     */
    public void setname(String newVal) {
        name = newVal;
    }

    public String getname() {
        return name;
    }

    /**
     * @param newVal
     */
    public void setResponsable(String newVal) {
        this.responsableId = newVal;
    }

    public String getResponsable() {
        return responsableId;
    }

    /**
     * @param newVal
     */
    public void setDeliverables(List<Deliverable> newVal) {
        this.deliverables = newVal;
    }

    public List<Deliverable> getDeliverables() {
        return deliverables;
    }

}