package com.inetpsa.pi201.domains.manageprojects.model.manageprojectsbudgetsresources.project;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.seedstack.business.domain.BaseEntity;

/**
 * Source code generated by EA, don't modify outside EA
 * 
 * @author THIPHAINE PEREZ ZANCA
 * @version 1.0
 * @created 18-mai-2016 10:06:26
 */
@Entity
public class Deliverable extends BaseEntity<Long> {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long deliverableId;

    private String name;
    private Date dateStart;
    private Date dateEnd;
    private Date dateNewStart;
    private Date dateNewEnd;
    private String comment;

    private String responsableId;

    // not available from outside of the aggregate
    Deliverable() {

    }

    public void finalize() throws Throwable {
        super.finalize();
    }

    @Override
    public Long getEntityId() {
        return deliverableId;
    }

    /**
     * @param newVal
     */
    public void setDeliverableId(Long newVal) {
        deliverableId = newVal;
    }

    public Long getDeliverableId() {
        return deliverableId;
    }

    /**
     * @param newVal
     */
    public void setname(String newVal) {
        name = newVal;
    }

    public String getname() {
        return name;
    }

    /**
     * @param newVal
     */
    public void setdateNewEnd(Date newVal) {
        dateNewEnd = newVal;
    }

    public Date getdateNewEnd() {
        return dateNewEnd;
    }

    /**
     * @param newVal
     */
    public void setdateNewStart(Date newVal) {
        dateNewStart = newVal;
    }

    public Date getdateNewStart() {
        return dateNewStart;
    }

    /**
     * @param newVal
     */
    public void setdateEnd(Date newVal) {
        dateEnd = newVal;
    }

    public Date getdateEnd() {
        return dateEnd;
    }

    /**
     * @param newVal
     */
    public void setdateStart(Date newVal) {
        dateStart = newVal;
    }

    public Date getdateStart() {
        return dateStart;
    }

    /**
     * @param newVal
     */
    public void setcomment(String newVal) {
        comment = newVal;
    }

    public String getcomment() {
        return comment;
    }

    /**
     * @param newVal
     */
    public void setResponsableId(String newVal) {
        this.responsableId = newVal;
    }

    public String getResponsableId() {
        return responsableId;
    }

}