package com.inetpsa.pi201.domains.manageprojects.model.manageprojectsbudgetsresources.user;

import org.seedstack.business.domain.GenericFactory;

/**
 * Source code generated by EA, don't modify outside EA
 * 
 * @author THIPHAINE PEREZ ZANCA
 * @version 1.0
 * @created 18-mai-2016 10:06:28
 */
public interface UserFactory extends GenericFactory<User> {

    /**
     * @param p_login
     * @param p_name
     * @param p_firstName
     */
    public User createUser(String pLogin, String pName, String pFirstName);

}