package com.inetpsa.pi201.manageprojects.rest.user;

import java.util.List;
import java.util.Map;

import org.seedstack.business.finder.Finder;
import org.seedstack.business.finder.Range;
import org.seedstack.business.finder.Result;

/**
 * Source code generated by EA, don't modify outside EA
 * 
 * @author FRANK DUPUY
 * @version 1.0
 * @created 24-juin-2016 09:25:57
 */
@Finder
public interface UserFinder {

    /**
     * @param p_range
     * @param p_criteria
     */
    public Result<UserRepresentation> findAllUser(Range pRange, Map<String, Object> pCriteria);

    /**
     * @param p_loginUser
     */
    public UserRepresentation findUserbyId(String pLoginUser);

    /**
     * find all user
     */
    public List<UserRepresentation> findAllUser();

}